# Site settings
title: Main Portfolio for1
description: 제 포트폴리오 사이트입니다

baseurl: ""          # 이 줄 꼭 넣으세요 (빈칸으로)
url: "https://jjobfor1-ux.github.io"

# User settings
username: STUDIO HS1
user_title: Refining complex ideas into functional reality
user_description: 
email: jjobfor1@email.com
github_username: jjobfor1-ux

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
